Generos -> Listas de generos
JoseBueno30/Dutify pull request #11
Opened 2024-05-14 09:24 UTC by VctPerez

2024-05-16 17:16 UTC, adriantd3 requested changes
No me corre porque creo que has borrado la api de jose y hay archivos en los que todavia se usa esa api

2024-05-17 11:30 UTC, adriantd3 requested changes
Los botones de los géneros me funcionan sin exagerar menos de la mitad de las veces. En mi caso he probado a darles rapido y lento. Falla de ambas formas.

Mira cómo se le asignan los id y los handlers a los de listas a ver si lo tienes distinto.
Con los de listas no falla pero tambien puede ser porque son menos.

Tambien tienes que quitarle el botón de añadir a las listas de los generos.

2024-05-18 14:42 UTC, JoseBueno30 commented
Por cierto, probando esto (q a mi al menos no me ha fallado) me he dado cuenta que deberíamos cambiar el color del body porque si no al recargar se queda en blanco. O puede que sea por el tamaño del componente de listas.

2024-05-18 21:36 UTC, adriantd3 approved these changes
Ya funciona 👍

Por cierto voy a hacer que el texto de las listCards sea mas pequeño porque no cabe el nombre de casi ninguna lista.

2024-05-20 09:36 UTC, merged