Esg cambio carousel
JoseBueno30/Dutify pull request #26
Opened 2024-05-26 10:44 UTC by ezee-sg

Cambios llevados a cabo:

- Cambio de carrusel (a uno en el que las que las imágenes se vean cuadradas).
- Cambios de accesibilidad en la página de inicio (para que las secciones se puedan tabear y leer durante la navegación).

Cuestiones:

- ¿Creeis que es necesario añadirle un caption a las imágenes del nuevo carrusel? Es que pienso que quedaría demasiado recargado (en las propias imágenes se ve el titulo de la playlist).
- Otra cosa, ¿cómo veis los colores de los puntos inferiores del carrusel? No sabía muy bien qué color ponerles para que hubiese contraste.

2024-05-26 13:00 UTC, JoseBueno30 requested changes
Me gusta mucho más que la versión anterior, pero veo que al final no has usado el componente que decidimos al final, ¿es porque con el componente que usas se puede hacer  algo que con el otro no? Es que veo que es algo excesivamente complicado para lo que se hacia relativamente fácil con el otro componente. Personalmente cambiaria el componente que se está usando.

En todo caso hay algunas cosas que habría que arreglar:

- La animación de pasar de uno a otro está bien pero el cambio de tamaño de la lista "seleccionada" es muy brusco, ocurre de forma abrupta nada más pulsar las flechas.
- Cuando estás en el ultimo ítem del carrusel el efecto de "seleccionado" ni siquiera ocurre.

Estas cosas se arreglarían simplemente usando el componente que habíamos decidido, además ese se puede hacer pasar clicando y arrastrando, que es más intuitivo también en la versión móvil

2024-05-26 18:16 UTC, DavidBuenoCarmona commented
![image](https://github.com/JoseBueno30/Dutify/assets/124664414/f0115c01-cec9-4f97-ade3-6d210a4c2944)
Salía error por el nombre del tabIndex en React, lo cambio yo.

2024-05-26 18:20 UTC, DavidBuenoCarmona commented
Al llegar al último item es cierto que no se agranda como los otros, desconozco como se podría arreglar 
![msedge_l5ZtTX2FkV](https://github.com/JoseBueno30/Dutify/assets/124664414/88a89435-9671-4c78-a128-acc068164fa7)

2024-05-26 18:21 UTC, DavidBuenoCarmona commented
Cuando se termina, sería bueno hacer un efecto de bucle y que no de un salto hacía atrás o hacia adelante. (Si se complica mucho lo podemos dejar así) 
![msedge_4qYZd9O3Io](https://github.com/JoseBueno30/Dutify/assets/124664414/ba2d10b8-1407-4cf7-ba56-b940d9f0254c)

2024-05-26 18:23 UTC, DavidBuenoCarmona commented
Sobre a tus cuestiones los colores los veo bien, pero habrá que verlos con la herramienta de accesibilidad a ver si hay que cambiarlos.

No creo que haga falta un caption para los elementos ya que se ve claro que lista es, pero para el modo ciegos se podría usar el nombre para identificar la lista

2024-05-27 06:28 UTC, adriantd3 requested changes
Esta muy bien ezequiel, me gusta mucho

Me parece un poco raro que cuando clickes una de las que estan en los lados no se transicione a esa posición:
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/f4508c06-ce42-4adc-8ebf-b2ac210bc660)

Solo los puntitos son interaccionables con el tab y ademas que no te dejan pulsarlos con el espacio.

Respondiendo a tus cuestiones:
- No, no hace falta el caption, es cierto que toda las listas ya tienen su nombre en la imagen
- Los colores probablemente los cambie para arreglar el tema del contraste, asi que no te preocupes.

2024-05-27 07:47 UTC, DavidBuenoCarmona commented
Trae la main a esta rama antes de mergear

2024-05-27 16:20 UTC, ezee-sg commented
He cambiado otra vez de carrusel (este ya es el definitivo) porque con este se arreglan algunas de las cuestiones en las que fallaba el anterior. Se que las transiciones entre la primera y la ultima hay un cambio brusco pero no he conseguido arreglarlo.

Lo único que está pendiente es la forma de navegar con el teclado (no es nada fácil de hacer).

Contadme como lo veis.

2024-05-31 09:29 UTC, DavidBuenoCarmona approved these changes

2024-06-03 06:59 UTC, adriantd3 requested changes
- Aparecen errores de accesibilidad por los aria en los headers de sección.
- Cuando recorres los carouseles usando tab y enter la imagen de en medio se raya y no se hace grande como cuando se hace con el raton.
- Es una tonteria pero cuando scrolleas el carousel desde el movil por mucho que lo muevas siempre te devuelve al siguiente.

2024-06-08 11:03 UTC, merged