Reproduccion de canciones
JoseBueno30/Dutify pull request #28
Opened 2024-05-26 20:54 UTC by VctPerez

2024-05-26 21:38 UTC, JoseBueno30 reviewed
Si reproduces una canción desde la barra de búsqueda, después no te deja reproducir canciones de la playlist.

También he visto que si una canción no tiene preview se reproduce la siguiente en su lugar, entiendo que es feature pero he encontrado una cosa un poco rara, tenia una playlist cuya ultima canción si tenia previw y la penúltima no, pero al borrar la ultima canción la penúltima seguía reproduciéndola incluso después de recargar la pagina.

Esto no se si es cosa del componente de MusicPlayer pero a veces pasa esto 
![image](https://github.com/JoseBueno30/Dutify/assets/124668506/49e45917-2dbb-464b-9557-9e3dc5aa5a27)

2024-05-26 21:42 UTC, JoseBueno30 commented
Había un pequeño fallo con el feedback de añadir una playlist a favoritas porque se había cambiado el nombre de playlist a playList en algunos sitios y no en otros, he arreglado  solo eso y lo pusheo

2024-05-27 06:10 UTC, adriantd3 requested changes
Esta increible victor.

Solo digo lo que ha puesto jose, lo de que hay canciones que se raya la imagen porque no es cuadrada (entiendo que esto es tema del music player). 

Lo otro que menciono es lo que ya te dije sobre las canciones que no tienen preview. No tiene sentido que aparezcan canciones con las que no puedes interaccionar. Yo haría que no saliesen directamente aunque entiendo que eso daría un monton de problemas.
Por lo menos pondría un popup indicando que la canción no tiene preview y que por tanto, se reproducira la siguiente que sí tiene.

2024-05-31 15:36 UTC, JoseBueno30 commented
- [ ] Al poner el modo en bucle, si reproduces otra canción de la playlist (he probado con la última) parece que se desactiva el bucle
- [ ] Hay que actualizar la playlist cuando ser recarge la lista, he implementado que al ñadir una canción desde el despegable la pagina se recarge pero esto afecta a la queue y no deja reproducir esa canción. 
- [ ] La playlist con el modo aleatorio y en bucle a la vez creo que no termina de funcionar (al menos parece que se para despues de reproducir algunas canciones).
- [ ] Si activas el modo random y despues lo desactivas sigue reproduciendo de forma aleatoria.
- [ ] Si activas el modo random al clickar sobre una canción se reproduce una de forma aleatoria de la playlist.
- [ ] Al activar el modo random, ir a cualquier otra pagina y después volver a una playlist el botón aparece como activo pero en realidad no lo está, con el loop no ocurre, en ese casi si que se mantiene activo.

2024-06-07 11:06 UTC, adriantd3 requested changes
- He probado a hacer lo siguiente y falla: Entrar una playlist, reproducir una canción, activar modo random, dejar que pase a la siguiente y clickar varias veces el boton de cancion anterior. Esto hace que no retroceda a mas canciones anteriores y que ademas no puedas saltar a la siguiente. Además, cuando se acaba la preview de la canción no pasa a la siguiente.
- Cuando reproduces una canción de una lista, vas a otra y le das a reproducir, no te deja volver a la canción de la playlist anterior.
- Cuando una canción no tiene preview, salta a la siguiente pero no te deja volver a la anterior, se resetea.
- Con la playlist en modo random, me ha llegado a pasar que la siguiente cancion ha sido la misma.
- Con una playlist de 3 canciones y en modo random, he contado que puedes reproducir 4 antes de que te corte. Esto lo he probado pulsando el boton de saltar cancion y dejandolo normal.
- Cuando se acaba la playlist, la ultima canción se queda rayada. Si quieres reproducirla de nuevo tienes que darle al boton de reproducir de songButton 2 veces o al boton de reproducir de abajo. En general en este estado esta bugueado, no te deja volver a la cancion anterior o pasar a una siguiente con el modo random. La unica solucion es darle al boton de reproducir lista.
- Si añades una nueva canción mientras se esta reproduciendo la lista, nunca llegará a esa nueva canción, ni con modo random o bucle. Además si le das a reproducir, se reproduce, pero no sigue a otras canciones de la playlist.

Esto es lo que he encontrado por ahora.

2024-06-07 17:01 UTC, adriantd3 approved these changes
Todo finisimo.👍

2024-06-08 10:17 UTC, merged