topBar v1.0
JoseBueno30/Dutify pull request #3
Opened 2024-05-01 11:02 UTC by VctPerez

Versión funcional de la barra superior para el prototipo.

2024-05-01 16:05 UTC, adriantd3 commented
Los estilos se mezclan. Haz merge desde la main antes para que tengas los estilos de listCard y genreCard actualizados.

Los componentes se descuadran un poco y la altura me falla.
Cuando haces hover sobre las pestañas el texto aparece un poco descentrado. Además, la animación es un poco lenta.
Prueba a darle un poco de font-weight al texto a ver que tal queda.

Los breakpoints y el estilo estan goz

2024-05-01 16:08 UTC, adriantd3 requested changes
Los estilos se mezclan. Haz merge desde la main antes para que tengas los estilos de listCard y genreCard actualizados.

Los componentes se descuadran un poco y la altura me falla.
Cuando haces hover sobre las pestañas el texto aparece un poco descentrado. Además, la animación es un poco lenta.
Prueba a darle un poco de font-weight al texto a ver que tal queda.

Los breakpoints y el estilo estan goz.

2024-05-02 10:52 UTC, adriantd3 approved these changes
Funciona correctamente.
Lo que no me gusta es la actitud de "si no funciona en tu ordenador, comprate uno nuevo".

2024-05-02 11:00 UTC, DavidBuenoCarmona approved these changes

2024-05-03 17:53 UTC, merged