Music Player Footer
JoseBueno30/Dutify pull request #4
Opened 2024-05-02 10:56 UTC by DavidBuenoCarmona

2024-05-03 18:04 UTC, adriantd3 approved these changes
Esta muy bien. Se nota el buen uso de flexbox 😏
Tengo 2 anotaciones:

- Esta es una tontería, ¿Por qué se ven así los bordes de la barra? Es un poco raro.
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/936bbdc4-e535-4e6a-b0dc-56171dcbee25)

- La versión móvil no tiene el reproductor centrado en la pantalla. Me resulta muy contra intuitivo. Debería ser como esta puesto en los prototipos.

2024-05-04 08:28 UTC, JoseBueno30 commented
Faltan los indicadores de tiempo bajo la barra y algún icono que indique que la barra de la derecha se usa para el volumen. Además de lo que ha dicho Adri de que la versión móvil no está como en figma.

2024-05-04 10:39 UTC, VctPerez commented
En mi opinion, los botones que has puesto están bien, pero me gusta mas el diseño que le dimos en figma  + añadirle algun tipo de feedback a los botones; que al pulsarlos cambien de color o, aumenten o disminuyan su tamaño, etc. :

Tu version 

> ![image](https://github.com/JoseBueno30/Dutify/assets/124668589/262ff423-57e8-41e8-820e-b32f8a2bd692) 

Figma 

> ![image](https://github.com/JoseBueno30/Dutify/assets/124668589/8e17cd97-7b07-4035-b7e9-6f9c70ed815c)
 (Además fijate que el botón de reproducir y/o pausar es mas grande).


Y En la barra del volumen hace falta indicarlo con un altavoz o algo 
Tu version:

> ![image](https://github.com/JoseBueno30/Dutify/assets/124668589/8071ff27-28cd-4926-85d9-e24a2d85adab)

Figma: 

> ![image](https://github.com/JoseBueno30/Dutify/assets/124668589/8cdda90d-2bf3-40d5-b2a2-23bba736506c)

Y como han dicho @JoseBueno30  y @adriantd3,  la versión de movil la cambiaría.

2024-05-07 12:17 UTC, adriantd3 requested changes
- El texto del nombre de la cancion esta pegado a la barra cuando la pantalla es lo suficientemente pequeña.
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/122761f9-748a-46d3-b320-9e268a104e3e)
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/179a4344-5021-4781-83f6-3ed62ed66b9e)


- Midudev te mataria por pillar cosas del DOM:
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/c42facf9-5b88-4252-b91d-920ca5d43006)

- Podrías poner en la izquierda de la barra lo que llevas de canción. Queda raro si sólo está en la derecha:
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/1f7dcdb1-e22d-4e2e-ba08-7ffb19e6c732)

- La imagen podría estar centrada para que no se quede a la izquierda cuando es pequeño + el texto de mm:ss se queda pegado a la pantalla
![image](https://github.com/JoseBueno30/Dutify/assets/124664550/0f711b5d-3923-4db3-bb3b-ac1436037a22)

2024-05-08 13:09 UTC, merged