Botón de ayuda implementado
JoseBueno30/Dutify pull request #8
Opened 2024-05-10 15:09 UTC by adriantd3

2024-05-10 15:35 UTC, VctPerez requested changes

2024-05-10 15:35 UTC, VctPerez commented on Dutify/src/components/topBar/helpButton/helpButton.jsx
> +function HelpButton({ visible }) {
Solo esta en modo claro. Yo le pondría modo oscuro para que haya consistencia con lo demás.

2024-05-10 15:42 UTC, VctPerez requested changes

2024-05-10 15:42 UTC, VctPerez commented on Dutify/src/components/helpModal/helpModal.jsx
> +function HelpModal() {
Solo está en modo claro. Yo le pondría también los colores del modo oscuro para mantener consistencia

2024-05-10 15:42 UTC, VctPerez commented on Dutify/src/components/helpModal/helpModal.jsx
> +              <li>Crear y editar nuevas listas de reproducción.</li>
Crear, editar y eliminar *

2024-05-10 15:42 UTC, VctPerez commented on Dutify/src/components/helpModal/helpModal.jsx
> +            <button
![image](https://github.com/JoseBueno30/Dutify/assets/124668589/32216b8c-3d73-4371-bfd9-845b1898d93d)
Veo redundante alguna de las dos opciones para cerrar la pestaña, quitaría alguna.
- Si dejas la x, ponla un poco más oscura de normal, en el modo claro, para que se diferencie mejor.

2024-05-11 10:12 UTC, DavidBuenoCarmona reviewed
Mergea la main en esta rama antes de terminar el PR

2024-05-11 10:12 UTC, DavidBuenoCarmona commented on Dutify/src/components/topBar/helpButton/helpButton.jsx
> +      style={{ aspectRatio: "1/1", height: "80%" }}
No deberíamos tener Css directamente sobre el html. Yo lo sacaría a un archivo css en esa misma carpeta. Por mantener el orden en el proyecto y tener las cosas localizables

2024-05-11 10:12 UTC, DavidBuenoCarmona commented on Dutify/src/App.css
> +  --color-theme:rgb(51, 162, 253);
Esto se ha cambiado también en la tarea de los modos (Claro y oscuro), te dará conflicto al mergear. El que esta en la otra tarea es el mismo color que tenemos en el figma. Comprueba si es el mismo que has puesto tu

2024-05-11 10:12 UTC, DavidBuenoCarmona commented on Dutify/src/App.css
> +  --color-theme:rgb(51, 162, 253);
Esto se ha cambiado también en la tarea de los modos (Claro y oscuro), te dará conflicto al mergear. El que esta en la otra tarea es el mismo color que tenemos en el figma. Comprueba si es el mismo que has puesto tu

2024-05-11 10:12 UTC, DavidBuenoCarmona commented on Dutify/src/components/helpModal/helpModal.jsx
> +              <li>Crear y editar nuevas listas de reproducción.</li>
Aunque eliminar sea una de las cosas que se puede hacer con las listas, no creo que se tenga que poner a la misma altura que crear y editar que si son acciones principales de la aplicación. Ya que un usuario usara Dutify para Crear y Editar, se puede eliminar pero no creo que sea tan principal

2024-05-11 10:12 UTC, DavidBuenoCarmona commented on Dutify/src/components/topBar/topBarStyle.css
> -#light .topBar{
Esto ha sido cambiado también el la otra tarea, revisalo al mergear

2024-05-11 11:17 UTC, adriantd3 commented on Dutify/src/components/helpModal/helpModal.jsx
> +function HelpModal() {
Hecho

2024-05-11 11:18 UTC, adriantd3 commented on Dutify/src/components/helpModal/helpModal.jsx
> +              <li>Crear y editar nuevas listas de reproducción.</li>
Lo he dejado por ahora en eliminar

2024-05-11 11:18 UTC, adriantd3 commented on Dutify/src/components/helpModal/helpModal.jsx
> +            <button
He dejado la x

2024-05-11 11:18 UTC, adriantd3 commented on Dutify/src/components/topBar/helpButton/helpButton.jsx
> +      style={{ aspectRatio: "1/1", height: "80%" }}
He arreglado eso

2024-05-11 11:18 UTC, adriantd3 commented on Dutify/src/App.css
> +  --color-theme:rgb(51, 162, 253);
Lo he puesto por el grupo

2024-05-11 11:19 UTC, adriantd3 commented on Dutify/src/App.css
> +  --color-theme:rgb(51, 162, 253);
Lo mismo

2024-05-11 11:33 UTC, VctPerez requested changes

2024-05-11 11:33 UTC, VctPerez commented on Dutify/src/App.css
> +  --color-theme:#623CEA;
En modo oscuro hay elementos que son dificilmente distinguibles

2024-05-11 11:36 UTC, VctPerez requested changes

2024-05-11 11:36 UTC, VctPerez commented on Dutify/src/components/topBar/topBarStyle.css
> +.btn-back{
En modo claro la flecha no debe ser blanca + el fondo tampoco se distingue muy bien

2024-05-11 12:15 UTC, VctPerez approved these changes

2024-05-11 12:15 UTC, VctPerez approved these changes

2024-05-11 12:15 UTC, VctPerez approved these changes

2024-05-11 12:16 UTC, VctPerez approved these changes

2024-05-11 12:17 UTC, VctPerez commented
El botón de la flecha no he mirado por qué es un rectangulo en vez de un cuadrado, pero eso no es para solucionarlo aquí

2024-05-11 15:09 UTC, merged